// me
export const myName = "I'm Yanhao Gong";
export const intro =
  "Currently a master student in Electrical Engineering at McGill University and actively seeking for a full-time or intern job in Software area.";

// education
export const schoolName = "McGill University";
export const eduIntro1 = "Master of Sci. Electrical Engineering";
export const Date1 = "Attending from Jan 2018 to May 2020 (Expected)";
export const eduIntro2 = "Bachelor of Eng. Electrical Engineering.";
export const Date2 = "Attending from Sep 2013 to Dec 2017";

// work
export const jobTitle = "Product Engineer Internship";
export const jobDetail =
  "I worked as a product engineer in Cadence Design System located at Shanghai from Jan to June in 2019. During that period, I built up multiple deep learning models using TensorFlow to focus on solving timing correlation problem between synthesis and posting routing steps, which are the main stages of digital verification. The goal is to give the prediction of static timing analysis resultts after routing with timing data obtained from GENUS(Front end Cadence EDA Tool) synthesis. Moreover, I helped with modifying the Tcl scripts of 5nm-level chip design, e.g. adding scripts parts for power and routing, fixing congestion and violations occured during implementation of unit case with INNOVUS (Back end Cadence EDA Tool).";

//projects
export const projectName = [
  "Circuit Uncertainty Quantification",
  "Image Picking Game Web Application",
  "Simple Web Budget Application",
  "Google Quick Draw Images Classification",
  "Ultrawide-Band CMOS Low-Moise Amplifier"
];

export const projectDetail = [
  "I constructed the stochastic collocation method in time domain in MATLAB with polynomial chaos and sensitivity analysis invoved, with which, circuit equations can be solved in a decoupled manner and time complexity is much less than Monte Carlo algorithm, but same accuracy maintained. Moreover, new model order reduction and sparse sampling method will be developed in the future.",

  "The website is built with React framework, which contains a homepage and sign up/in components, a download option is under development. Both web-view and android mobile version of this game are created. Data that generated by users’ operation on our website will be collected and sent back to database constructed with MySQL.",

  "I built a budget web application in JavaScript, in which monthly income and expense can be listed in website with user input and an overall budget can be returned simultaneously.",

  "This is a project from applied machine learning course. I constructed the pre-processing method and multiple models e.g. convolutional neural network and XGBoost in Python to achieve higher accuracy of classifying images into different categories compared to baseline such as LinearSVM.",

  "The digital circuit model of the low-noise amplifier consist of three stages: Chebyshev Filter, Cascode configuration and Buffer, with a bandwidth range of 3.1 to 10.6 GHZ on ADS was built and achieved an overall gain of 10dB."
];

// contact
export const email = "yanhaogong@gmail.com";
export const phoneNumber = "514-623-0912";
